//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ON4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Numbers1
    {
        public string Table_Number1 { get; set; }
        public int NumberofLayersId { get; set; }
        public string ControlAddress { get; set; }
        public string Port_diection { get; set; }
    }
}
