//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ON4
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_balance
    {
        public string Table_number { get; set; }
        public string Names { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Quota { get; set; }
        public Nullable<int> NumberofLayersId { get; set; }
        public string Room_No { get; set; }
    }
}
