//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ON4.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string timer {
            get {
                return ((string)(this["timer"]));
            }
            set {
                this["timer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Recording {
            get {
                return ((string)(this["Recording"]));
            }
            set {
                this["Recording"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ControlComName {
            get {
                return ((string)(this["ControlComName"]));
            }
            set {
                this["ControlComName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cboPot1 {
            get {
                return ((string)(this["cboPot1"]));
            }
            set {
                this["cboPot1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cboPot2 {
            get {
                return ((string)(this["cboPot2"]));
            }
            set {
                this["cboPot2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cboPot3 {
            get {
                return ((string)(this["cboPot3"]));
            }
            set {
                this["cboPot3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cboPot4 {
            get {
                return ((string)(this["cboPot4"]));
            }
            set {
                this["cboPot4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cboPot5 {
            get {
                return ((string)(this["cboPot5"]));
            }
            set {
                this["cboPot5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cboPot6 {
            get {
                return ((string)(this["cboPot6"]));
            }
            set {
                this["cboPot6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cboPot7 {
            get {
                return ((string)(this["cboPot7"]));
            }
            set {
                this["cboPot7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cboPot8 {
            get {
                return ((string)(this["cboPot8"]));
            }
            set {
                this["cboPot8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 启用继电器控制 {
            get {
                return ((bool)(this["启用继电器控制"]));
            }
            set {
                this["启用继电器控制"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 启用清零 {
            get {
                return ((bool)(this["启用清零"]));
            }
            set {
                this["启用清零"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 启用检定 {
            get {
                return ((bool)(this["启用检定"]));
            }
            set {
                this["启用检定"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("全部")]
        public string 记录楼层 {
            get {
                return ((string)(this["记录楼层"]));
            }
            set {
                this["记录楼层"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 启用计费 {
            get {
                return ((bool)(this["启用计费"]));
            }
            set {
                this["启用计费"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 启用自动记录 {
            get {
                return ((bool)(this["启用自动记录"]));
            }
            set {
                this["启用自动记录"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string 从__点到 {
            get {
                return ((string)(this["从__点到"]));
            }
            set {
                this["从__点到"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string @__开始自动记录 {
            get {
                return ((string)(this["__开始自动记录"]));
            }
            set {
                this["__开始自动记录"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("一个")]
        public string 每隔__小时记录一次 {
            get {
                return ((string)(this["每隔__小时记录一次"]));
            }
            set {
                this["每隔__小时记录一次"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 自动连接串口 {
            get {
                return ((bool)(this["自动连接串口"]));
            }
            set {
                this["自动连接串口"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM51")]
        public string 楼层五串口 {
            get {
                return ((string)(this["楼层五串口"]));
            }
            set {
                this["楼层五串口"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM61")]
        public string 楼层六串口 {
            get {
                return ((string)(this["楼层六串口"]));
            }
            set {
                this["楼层六串口"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM52")]
        public string 五层阀门串口 {
            get {
                return ((string)(this["五层阀门串口"]));
            }
            set {
                this["五层阀门串口"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM62")]
        public string 六层阀门串口 {
            get {
                return ((string)(this["六层阀门串口"]));
            }
            set {
                this["六层阀门串口"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM31")]
        public string 楼层三串口 {
            get {
                return ((string)(this["楼层三串口"]));
            }
            set {
                this["楼层三串口"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM41")]
        public string 楼层四串口 {
            get {
                return ((string)(this["楼层四串口"]));
            }
            set {
                this["楼层四串口"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM32")]
        public string 三层阀门串口 {
            get {
                return ((string)(this["三层阀门串口"]));
            }
            set {
                this["三层阀门串口"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM42")]
        public string 四层阀门串口 {
            get {
                return ((string)(this["四层阀门串口"]));
            }
            set {
                this["四层阀门串口"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 启用费用编辑 {
            get {
                return ((bool)(this["启用费用编辑"]));
            }
            set {
                this["启用费用编辑"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 启用缴费编辑 {
            get {
                return ((bool)(this["启用缴费编辑"]));
            }
            set {
                this["启用缴费编辑"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 启用缴费删除 {
            get {
                return ((bool)(this["启用缴费删除"]));
            }
            set {
                this["启用缴费删除"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 启用费用统计编辑 {
            get {
                return ((bool)(this["启用费用统计编辑"]));
            }
            set {
                this["启用费用统计编辑"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 启用费用统计删除 {
            get {
                return ((bool)(this["启用费用统计删除"]));
            }
            set {
                this["启用费用统计删除"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 允许修改额度 {
            get {
                return ((bool)(this["允许修改额度"]));
            }
            set {
                this["允许修改额度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string 小时触发 {
            get {
                return ((string)(this["小时触发"]));
            }
            set {
                this["小时触发"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string 时间间隔 {
            get {
                return ((string)(this["时间间隔"]));
            }
            set {
                this["时间间隔"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string 读表失败处理时间 {
            get {
                return ((string)(this["读表失败处理时间"]));
            }
            set {
                this["读表失败处理时间"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM30")]
        public string 三层阀门串口2 {
            get {
                return ((string)(this["三层阀门串口2"]));
            }
            set {
                this["三层阀门串口2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM40")]
        public string 四层阀门串口2 {
            get {
                return ((string)(this["四层阀门串口2"]));
            }
            set {
                this["四层阀门串口2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM50")]
        public string 五层阀门串口2 {
            get {
                return ((string)(this["五层阀门串口2"]));
            }
            set {
                this["五层阀门串口2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM60")]
        public string 六层阀门串口2 {
            get {
                return ((string)(this["六层阀门串口2"]));
            }
            set {
                this["六层阀门串口2"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=Calorimeter1;User ID=sa;Password=123")]
        public string Calorimeter1ConnectionString {
            get {
                return ((string)(this["Calorimeter1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=Calorimeter1;User ID=sa;Password=123")]
        public string Calorimeter1ConnectionString1 {
            get {
                return ((string)(this["Calorimeter1ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int 读取延时时间 {
            get {
                return ((int)(this["读取延时时间"]));
            }
            set {
                this["读取延时时间"] = value;
            }
        }
    }
}
